Merged PR 125: add one more repository
Увидел что чет не так при установке gdal

ERROR: unsatisfiable constraints:
  so:libgeos_c.so.1 (missing):
    required by: gdal-2.4.2-r1[so:libgeos_c.so.1]
The command '/bin/sh -c apk add       --no-cache       --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing       --repository http://dl-cdn.alpinelinux.org/alpine/edge/main       gdal' returned a non-zero code: 2

Related work items: #499